project:
  type: book
  execute-dir: project
  output-dir: docs

execute: 
  freeze: auto

book:

  title: "Virginia Beach Housing Study Update"
  repo-url: https://github.com/housingforwardva/virginia-beach
  output-file: "virginia-beach-housing-study-update"
  downloads: docx
  author:
    - name: Virginia Center for Housing Research
      url: https://mlsoc.vt.edu/research/vchr.html
    - name: HousingForward Virginia
      url: https://housingforwardva.org/
  date: today
  date-format: long
  
  chapters:
    - index.qmd
    #- test.qmd
    - executive-summary.qmd
    - preface.qmd
    - part: "Introduction"
      chapters:
        - intro.qmd
        - data-methods-notes.qmd
    - part: "Data findings"
      chapters:
        - hh-trends.qmd
        - market.qmd
        - affordability.qmd
        - conclusions.qmd
    - part: "Solutions"
      chapters:
        - current-efforts.qmd
        - solutions-overview.qmd
    - part: "Strategic priorities"
      chapters:
        - sp-htf.qmd
        - sp-vbda.qmd
        - sp-education.qmd
    - part: "Easy wins"
      chapters:
        - ew-haf.qmd
        - ew-clt.qmd
    - part: "Background work"
      chapters:
        - bw-mumi.qmd
        - bw-permits.qmd
        - bw-advisory.qmd
    #- references.qmd
  
  appendices: 
    - a1-engagement.qmd
    - a2-workforce.qmd
    - a3-noah.qmd

format:

  html:
    theme:
      - lumen
      - hfv-custom.scss
    grid: 
      sidebar-width: 375px
    fontsize: "100%"
    #template-partials:
    #  - toc.html
    toc-title: "On this page"
    
  docx: 
    toc: true
    toc-depth: 1
    number-sections: true
    reference-doc: hfv-report-template.docx
    fig-align: left
    filters: 
      - hfv-colors.lua
    
  #pdf:
  #  documentclass: scrreprt
  #  mainfont: "Open Sans"
  #  fig-pos: "H"
  #  include-in-header:
  #    text: |
  #      \usepackage{float}
  #      \raggedbottom

bibliography: references.bib