# Conclusions

Housing market conditions have improved substantially since 2014. A slower pace of building since 2016 coupled with increasing demand from the two largest living generations (boomers and millennials) has balanced the market, encouraging housing investments across the City. The City needs to keep adding units to maintain housing market health. Because there isn’t excess demand pressure, the City has an opportunity to strategically address housing needs and increase the diversity of the housing stock. 

Affordable, attainable housing is the City’s most critical need. The highest levels of housing insecurity are among extremely low- and very low-income renters, as well as senior householders 75 and older. Additional housing dedicated to low-income households is required to stabilize households experiencing housing insecurities and to reduce periods of homelessness among Virginia Beach residents. Purpose-built senior housing and permanent supportive housing, along with services to support households, would support this critical need.

Homeownership opportunities for low- and moderate-income households will further stabilize Virginia Beach households and help retain workers. Homeownership is critical to wealth-building, and the City can help ease housing transitions and upgrades by creating straightforward steps from committed affordable rental housing to equity-building opportunities. These steps would support the City’s economic and social systems by stabilizing lower-wage workers and promoting worker retention. Workers are likely to leave the City if they cannot find affordable housing that meets their needs throughout their lives and do not have the opportunity to build wealth that will benefit generations to come. 

Though the Virginia Beach market is healthy, it’s trending toward tightness and housing shortage. Stakeholders already recount evidence of how the most vulnerable households are being excluded from the market. Aggressive development of dedicated affordable housing will benefit the market by relieving pressure on median-priced rental housing and the most affordable homeownership opportunities. It will also prevent the tightening market from incentivizing cursory housing “flips” intended to capitalize on higher rents and desperation of the most vulnerable renters. 

Increasing market health encourages investment in owner-occupied homes because homeowners will feel more confident that they can recoup investments if they choose to sell their home. However, some households don’t have the resources to make those investments. Cost-burdened owners may defer maintenance and forgo upgrades, so support for existing homeowners will similarly support housing preservation efforts while improving their quality of life.

The following chapters of this report details the study team’s recommendations for the City. The solutions respond to market conditions and specific challenges identified in the study process. Each of the approaches has been vetted with Virginia Beach staff and introduced to the City Council. The study team developed the details of these solutions based on best practices, resources available in the City and the state, as well as specific guidance from staff and the council.
