# Executive summary {.unnumbered}

Virginia Beach’s housing market has progressed since 2016, showing both positive growth and emerging challenges. Home prices are rising yet remain reasonably accessible. The pace of sales and vacancy rates indicates market balance. However, increasing market tightness presents challenges, notably the scarcity of affordable homes for low-income families. The study outlines these trends and proposes policy solutions to ensure housing opportunities for all.

::: callout-note
The original 2016 report (*Virginia Beach Housing Needs Assessment, Market Analysis, and Re-Investment Study*), along with the full version of this study update, are available on the Department of Housing & Neighborhood Preservation page of the City’s website: [**VirginiaBeach.gov/HousingStudy**](https://www.VirginiaBeach.gov/HousingStudy)
:::

## Market strengths

The city’s housing market is healthier now than in 2016. The median price of homes has increased by 36%, indicating strong demand, and homes typically remain on the market for 40 days, indicating a balanced market. This balance benefits both sellers, who can expect to sell their homes within a reasonable period at a good price, and buyers, who have the luxury of time to explore multiple options without pressure.

In the rental sector, a 5% vacancy rate also suggests a well-balanced market, providing renters with a variety of well-managed properties to choose from and ensuring efficient lease-up times for property managers. These trends indicate a housing market that is stable and accommodating for most participants in the current scenario.

## Emerging challenges

Despite these positive trends, Virginia Beach now faces significant affordability and accessibility challenges. A critical concern is the lack of rental units affordable to very-low-income households, many of whom are employed in the city’s top 10 most common occupations. These individuals often bear the burden of high housing costs to remain in the city. Additionally, a shortage of units for above-average earners creates undue pressure on moderately priced housing stock.

Limited homeownership opportunities for low- and moderate-income households represent another pressing issue. The tightening market, coupled with today’s less favorable mortgage options, places these potential buyers at a disadvantage. The inability of working households to build wealth through homeownership could prompt them to seek housing in other areas, adversely impacting the local workforce and business retention in Virginia Beach.

## New solutions

When working households don’t have the opportunity to find an affordable apartment or buy a home and build wealth in Virginia Beach, they will seek housing elsewhere. This makes it hard for businesses and other essential public services --- including schools and hospitals --- to attract and retain workers. Virginia Beach must address its housing gaps by adding suitable, attainable options. This study presents eight policy and program solutions in three categories:

[Strategic priorities]{.hfv-grass-bold}

Strategic priorities focus on long-term systemic change. They include establishing a Housing Trust Fund as a sustainable financial backbone for affordable housing initiatives and using recently expanded powers of the City of Virginia Beach Development Authority to develop large-scale projects that simultaneously stimulate economic growth and affordable housing opportunities. In addition, a well-designed housing education campaign would give residents a rich, well-informed perspective on housing issues across Virginia Beach.

[Easy wins]{.hfv-shadow-bold}

Easy wins offer quicker, more straightforward solutions that can make an immediate difference. Creating a new Housing Assistance Fund would directly benefit workers and their families who may be struggling to find homes that meet their needs and budgets. Leveraging the Virginia Statewide Community Land Trust could also bring near-term benefits by introducing permanently affordable homeownership opportunities.

[Background work]{.hfv-desert-bold}

Background work includes important tasks needed within current and future planning efforts to prime Virginia Beach’s core operations in support of its long-term housing goals. These include exploring self-sustaining financing models for mixed-income, mixed-use developments; streamlining permitting and review processes; and establishing a diverse stakeholder group to transform housing elements of the City’s comprehensive plan into new zoning regulations that promote --- not hinder --- housing affordability.

The full descriptions of each solution offer realistic implementation steps for City leaders, staff, and other partners to follow. While these recommendations are tailored specifically to Virginia Beach, relevant examples of best practices from different communities --- both in Virginia and in other states --- are included for inspiration.

Informed by thorough analysis of housing market dynamics and meaningful community engagement, this study is a roadmap to lead Virginia Beach toward greater economic opportunity and community stability by making it easier for residents to find, afford, and thrive in their homes.

<!-- {{< pagebreak >}} -->
