# Develop a City-managed Housing Trust Fund

### STRATEGIC PRIORITY 1 {.unnumbered .unlisted}

### Develop a City-managed Housing Trust Fund {.unnumbered .unlisted}

A major barrier to affordable housing production in Virginia Beach is a shortage of capital with limited regulatory hurdles. A Virginia Beach Housing Trust Fund (HTF) would create a pool of capital that provides gap funding for a wide range of affordable housing projects in the city, including both rental and homeownership.

Local HTFs aren’t new in Virginia. Other cities like Alexandria and Richmond use them to provide flexible and vital funding for affordable housing developments when federal and state resources fall short. 

HTFs can be capitalized by both public and private sources. Funding is awarded through a competitive process to ensure that development is meeting the needs and standards of the community. A locality may provide both grants and loans with flexible terms.

## HOW IT WORKS

To build a successful HTF, the City will need to decide how the fund will be funded, governed, and administered. Below are nine program design elements that describe the major components of HTF operations.

*Legal structure*

HTFs are chartered by local governments through an enabling ordinance or law. Establishing the fund’s specific legal structure sets a clear purpose for funds, assigns core responsibilities, and gives power to distribute funding.

There are several possible avenues for incorporating an HTF, including:

* Wholly operating as a local government program (most common)
* Delegating authority to an existing or new quasi-public body, such as a housing authority or regional commission
* Delegating authority to an existing or new nonprofit organization
* Using a public-private hybrid model

The most appropriate option for Virginia Beach will likely be to create a HTF as a program administered by the Department of Housing and Neighborhood Preservation.

*Governance and oversight*

In general, HTFs are either entirely or predominantly composed of public dollars. Therefore, HTFs require proper governance and oversight to set funding levels and priorities and to make award decisions. These actions should balance public transparency with efficiency.

Important governance and oversight-related decisions include:

* Choosing whether to assign fiduciary responsibility to an existing public body (e.g., the City Council), a new public body (e.g., appointed advisory board), or defining distinct roles for both
* Creating regulations to conform to Virginia open meeting laws, as applicable
* Establishing avenues for collecting and using public input
* Determining processes for fiscal audits and other regular checks and balances to ensure public trust

One option for Virginia Beach would be to use the existing Housing Advisory Board (HAB) as the body for working with staff to design the HTF and evaluate applications. The HAB could make non-binding award recommendations to the City Council, who would be responsible for final approvals.

*Administration and overhead*

While a legal structure provides a broad outline of how an HTF will function, the successful administration of an HTF requires capable staff and funding to operate and sustain the fund. Administrative staff is typically housed within a local government department, nonprofit organization, or a newly established entity.

Important administrative decisions include:

* How operations of the HTF governing body/bodies are supported
* How overhead costs are estimated and covered
* Who serves as day-to-day financial stewards of the HTF monies
* Who accepts, reviews, and recommends applications for approval
* Who monitors awardees for compliance and success

If the HTF is housed within the City, department leaders and the City Council should determine the expected increase in staff workload to make appropriate investments in new positions.

*Strategic partnerships*

Successful HTFs aren’t developed and sustained within a bubble. Robust partnerships with housing organizations can facilitate a strong HTF that consistently meets the needs of clients served by the local affordable housing industry. These partnerships can lead to a steady and increasing applicant pool, resulting in higher standards through competition. Other important community organizations also have a vested interest in housing and can help strengthen HTFs with additional funding, complementary resources, and political support.

HTF stakeholders should conduct strategic outreach to:

* For-profit and nonprofit housing developers
* Housing, homelessness, and other social service providers
* Anchor institutions, including universities, major employers, and philanthropic foundations
* Grassroots community groups and faith-based organizations
* Related trade and advocacy associations, such as business leagues

*Funding amounts and sources*

A HTF needs financial seeding to get off the ground, but long-term financial sustainability is just as important. HTFs require a dedicated revenue source that comes either from an annual budget appropriation or through a revenue source such as real estate transfer taxes or developer fees. Determining funding levels is contingent on community needs and requires an understanding of housing needs.

Important funding-related decisions include:

* Choosing whether to make annual appropriations through a regular budgeting process or to establish a dedicated source of funds
* Confirming  the initial funding level for the HTF
* Identifying potential revenue sources (e.g., taxes and fees, interest, sale or lease of government property)
* Determining funding levels through housing need assessments, housing provider surveys, or comparable program applications

The potential funding section below has more specific information on funding sources for Virginia Beach to explore.

*Types of housing activities funded*

While many existing housing programs focus on a specific housing activity such as weatherization or new construction, HTFs can act more broadly depending on community priorities. The broad ability of HTFs to fund different activities can ensure that all aspects of a community’s housing needs are addressed, while also filling the void where other housing programs may fall short.

Possible uses for HTF funding include, but are not limited to:

* Equity to support the creation or preservation of affordable rental housing
* Revolving low- or zero-interest loans to help finance affordable housing development
* Land acquisition grants
* Homebuyer assistance for down payments, closing costs, and other expenses
* Rehabilitation, energy efficiency, and weatherization projects
* Operational support for homelessness prevention and related services
* Matching grants for CDBG, HOME, and other federal or state funds

*Income and household priorities*

Communities can support their members most in need by setting income and household priorities. This allows for more flexibility and responsiveness than other state and federal programs can offer. Definitions for income ranges and households served are often defined in enabling legislation, but priorities may change over time to reflect a community’s evolving needs.

HTF resources can be prioritized in several ways:

* Targeting homeownership, rental, homelessness, or some combination of those needs
* Focusing on new supply or improving/preserving existing housing stock
* Concentrating on extremely or very low-income households, or promoting a broader range of affordability

Based on the affordability analysis earlier in this report, Virginia Beach should likely focus its HTF on the creation of new rental homes affordable to households below 50% AMI. Additional priorities should include affordable senior housing and permanent supportive housing. These projects are some of the most difficult to successfully finance due to the additional investments needed per unit.

*Award criteria and application scoring process*

A structured application and scoring process for partners will ensure an efficient and transparent use of funds. HTF administrators are responsible for establishing this process, as well as developing criteria for potential applicants. A successful HTF is a two-way street and requires strong partners to make sure funds are used properly.

Relevant decisions to make for this program design element include:

* Determining who gets to establish criteria and how
* Deciding whether criteria will be regularly re-evaluated with public feedback
* Establishing minimum requirements for applicants (e.g., years incorporated, annual budget, legal status)
* Choosing the application and award schedule (e.g., annual cycle, rolling basis)
* Outlining the decision-making process from submission to final award

*Financial sustainability*

Virginia Beach’s housing challenges were not created in the course of only a few years, so efforts to solve these problems will likewise take time. One major consideration for HTFs is how to maintain or increase funding beyond any initial startup investments.

Important actions to ensure fund sustainability include:

* If funding is allocated each year (i.e., no dedicated revenue), determining how to make it a consistent priority for policymakers
* If there is a dedicated source of revenue, analyzing potential threats and challenges to those collection streams (e.g., if using a meals tax, what would happen in another pandemic?)
* Investigating ways to diversify revenue sources, such as corporate and philanthropic gifts
* Understanding the differences between and weighing costs/benefits for pure grants versus low-to-zero interest loans, which are paid back to the fund

Designing the HTF as a revolving fund would likely be the most appropriate approach to maximize the City’s investments. The fund can provide working capital to affordable housing developers at rates well below market, paired with repayment schedules that allow the project to sustainably transition to permanent financing.

## HOW TO DO IT

**Within 6 months:**

* Create a task force to guide the design and creation of the HTF. This group should pull from existing experts and leaders, especially the Housing Advisory Board and ideally one or two members of the City Council.
* Design a curriculum to guide the task force throughout the HTF development process. The program design elements described above can be a starting point.
* Determine a meeting schedule for the task force, along with clear plans for receiving input from other partners and the public.
* Start the task force work on legal and governance decisions so that core design aspects are agreed upon early in the process.
* Engage other localities with HTFs in Virginia (and elsewhere) to ask specific questions and learn from their successes or challenges.

**Within 1 year:**

* Determine the level of support that is achievable with city general funds in the next two years.
* Explore the potential for “dedicated” sources of revenue for the fund; consider administrative fees associated with real estate transactions.
* Identify and recruit additional sources of capital—including participation from lending institutions, corporations, and charitable foundations.
* Develop a set of ideal projects that the HTF may serve based on housing type (e.g., rental, homeownership, supportive housing) and client type (e.g., income level, age, household type)
* Determine whether the program will provide loans, grants, or both and at what levels. Base this determination on the ideal projects served and their anticipated needs.
* Convene potential HTF applicants for feedback and begin drafting application and scoring criteria.

**Within 2 years:**

* Draft any and all necessary award documentation, including underwriting material and development agreements.
* Make the first dedicated allocations into the HTF and establish a schedule for the first award cycle.
* Launch the HTF and begin taking applications. If desired, conduct feedback sessions with interested applicants to answer questions and provide guidance on their submissions.
* Proceed with the formal decision process and select projects to award. Execute contracts.
* Track and monitor progress to ensure compliance; make modifications as needed.

## WHO DOES WHAT

**City staff:** Help organize and support task force, (likely) serve as HTF administration to manage funds and process applications.

**HTF task force:** Take lead role in designing HTF, liaison with the City Council and other partners, support staff with specific tasks.

**Housing Advisory Board (or similar entity):** Assume permanent responsibility for overseeing HTF and reviewing applications with staff, make recommendations to the City Council.

**City Council:** Participate in and oversee task force, make decisions about funding types and levels, evaluate and approve HTF award recommendations.

## FUNDING SCOPE

* To have any significant impact, the initial HTF capitalization should be at least $1,000,000 per year. This level of funding would allow for a range of housing projects to be supported annually. Most HTFs in the state are capitalized at levels that meet or exceed this amount.
* Based upon anticipated funding levels, the HTF should set production goals for a period of 3-5 years. Because developing and fully funding complex affordable housing projects (especially rental communities) can take lengthy periods of time, these projects will frequently carry over from one year to the next. The HTF should set goals for commitment as well as completion of housing units per year over a 3-5-year window.
* The HTF will need to establish clear criteria for project readiness in order to avoid locking up funding for projects for a year or years before construction begins.
* To support and build a pipeline, the HTF may wish to allocate some of its funding for predevelopment activities. These funds need to be flexible and forgivable in the event that a project does not move forward.

## POTENTIAL FUNDING SOURCES

**Low barrier options:**

To get the HTF started—while longer-term solutions are explored—Virginia Beach can consider both general funds and its existing allocation of federal housing and community development dollars. These two sources are the most common options found in HTFs throughout Virginia.

*General fund appropriation*

General funds are used by nearly every HTF in the commonwealth, usually to supplement other sources. However, they can be an important starting point, since the City Council has full authority to allocate these dollars within the context of annual budget planning. While this flexibility is desirable, it also means that funds are at risk of disappearing should non-dedicated revenues decline and/or City funding priorities change.

*Federal funds*

Several localities in Virginia also include CDBG, HOME, and other federal housing grants in their HTFs. These funds are more reliable than general funds but are subject to program requirements outside City control. They are also not “new” funds—the Department of Housing and Neighborhood Preservation already distributes these grants each year. Therefore, the main purpose of including federal funds in HTFs is to consolidate application processes for a streamlined funding system. 

**Dedicated sources:**

Dedicated revenue sources are a prerequisite for successful HTFs. These sources typically rely on a special tax or fee created specifically to fund housing investments. This stability is highly desirable, but must be planned with respect to a locality’s overall fiscal position—alongside more challenging political barriers as well.

*“Penny” (or more) on real estate tax*

One of the most common dedicated sources of revenue for HTFs is a supplemental assessment on local real estate taxes. This is often an additional \$0.01 collected per \$100, on top of the base real estate tax rate. Based on projections in the [proposed FY 2023-2024 operating budget](https://s3.us-east-1.amazonaws.com/virginia-beach-departments-docs/budget/Budget/Proposed/FY24-Proposed-Operating-Budget.pdf), an additional cent on the real estate tax in Virginia Beach would generate over \$7,000,000.

*New development extractions*

Several localities in Virginia use new residential development (or other types of development) to help fund their HTFs. Incorporating “in lieu fees” as an option for the city’s Workforce Housing Program would likely be the most consistently effective mechanism, in addition to avoiding legal challenges. To receive a density bonus, developers could provide a financial contribution to the HTF as an alternative to providing on-site affordable units. Alexandria currently uses this as a successful revenue source. However, this option hinges on the Workforce Housing Program being widely adopted by new residential development across the city.

Alternatively, Virginia Beach may pursue voluntary “[linkage fees](https://nvaha.org/wp-content/uploads/NVAH_1311_CommImpactRpt-WEB.pdf)” for commercial development. These fees are always negotiated on a project basis. For example, Fairfax County recommends a $3.00-per-square-foot surcharge for commercial development in Tysons Corner. The proceeds support the development of affordable and workforce housing in Tysons.

*Transactional fees*

While special taxes or fees on certain purchases and other economic activity are frequently used to fund HTFs, non-housing uses are more common. Examples include real estate transfer taxes, meals taxes, and hotel taxes. These options may be more palatable than a real estate tax increase but are usually more sensitive to volatile economic conditions. Virginia Beach should evaluate its current array of targeted taxes to determine the best opportunities for capturing additional revenue for housing.

::: callout-tip
### Special Revenue Funds

Virginia Beach already has several Special Revenue Funds (SRF) that connect specific income streams with specific uses.

* **Parks and Recreation Special Revenue Fund:** Collected from user fees and a portion of real estate taxes. Estimated to be over $32,000,000 in FY 2023-2024.
* **Tourism Investment Program Fund:** Collected from 5% of the hotel tax, half the \$2.00 Hotel Flat Tax, 1.06% of the meals tax, \$0.05 per pack of the cigarette tax, and all the amusement tax. Estimated to be over \$61,000,000 in FY 2023-2024. 
:::

**High-impact solutions:**

Transformational investments in affordable housing are usually debt-financed. While still uncommon in Virginia, bonds specifically for housing are increasingly being issued by local governments in other states. This option may not be appropriate for Virginia Beach in the near future, so the City should also investigate an alternative approach newly authorized by state law.

*Virginia Resources Authority*

In 2023, the General Assembly adopted HB1805/SB1401, which adds affordable housing to the list of projects eligible to be financed by the Virginia Resources Authority (VRA). For localities with high bond ratings (such as Virginia Beach), municipal bonds issued by VRA have no impact on bond capacity.

Virginia Beach has previously partnered with VRA to finance $6,000,000 for the [Lynnhaven Oyster Restoration and Estuary Protection project](https://www.virginiaresources.gov/portfolio/projects/11/land-conservation-in-virginia-beach). While VRA is still evaluating how to support activities that support affordable housing as of October 2023, officials recommend that any interested locality proactively contact them to explore options.[^vra]

[^vra]: Based on interview with Shawn Crumlish, Executive Director of the Virginia Resource Authority, August 2023.

*General obligation bonds*

Should Virginia Beach’s future fiscal priorities present the opportunity, the City can explore issuing its own general obligation (GO) bonds to raise capital for the HTF.

::: callout-note
#### Using GO bonds

Because GO bonds are secured by general revenue and not a specific income stream (e.g., public utility service fees), orienting a portion of the city’s tax-supported debt to a new priority is a major long-term strategic decision. Housing needs should be evaluated against concurrent public investment needs, such as hard infrastructure and school facilities, and incorporated into the city’s debt management policy and capital improvement plan (CIP) accordingly.
:::

Historically, Charlottesville, Harrisonburg, and Alexandria have been the [only Virginia localities](https://dmz1.dhcd.virginia.gov/HB854/part-5-bondfinancing.html#local-bond-options) to use GO bonds for housing. However, Richmond [recently committed](https://drive.google.com/file/d/1VFbPnG929ovCbz4NyEcBVRfFNhxWkIaX/view?usp=sharing) $50,000,000 in bond revenue over five years to accelerate affordable housing production. LISC has also partnered with the city to leverage an additional \$50,000,000.

*Private and philanthropic support*

A wide range of nonpublic funding sources support affordable housing. These include banks and other financial institutions that provide low-cost loans and grants, as well as investments by corporations and philanthropic foundations. More recently, community anchor institutions (including hospital systems, colleges and universities, and churches) are also finding ways to support affordable housing through monetary gifts and land donations.

However, private sources are rarely “mixed” into publicly operated HTFs, and instead serve as separate complements. HTFs that are managed by quasi-public or nonprofit organizations can more easily blend public and private dollars into a single fund, but these cases are rare.

Therefore, should Virginia Beach’s HTF be operated in full by the City, private and philanthropic sources can augment these efforts by:

* Providing matches to public investments, especially to cover discrete activities (e.g., site planning, community amenities, support services)
* Funding experimental approaches and pilot projects (e.g., innovative construction methods)
* Proactively designing special low-interest loans and lines of credit that easily pair with HTF awards

## METRICS TO EVALUATE SUCCESS

The success of an HTF can be measured by both what it does (outputs) and what impact it’s able to have (outcomes). Outputs refer to the tangible deliverables and activities generated by the HTF, while outcomes capture the broader impact and effectiveness of the fund. Importantly, outcomes can help determine whether the HTF is effectively addressing the priority challenges it was designed to address.

Below are suggested examples to measure both.

**Outputs:**

* Number of housing units created or preserved
* Locations of homes across city
* Cost metrics (e.g., per-unit subsidy, total development costs)
* Funding leveraged
* Time to completion and occupancy

**Outcomes:**

* Beneficiary demographics
* Affordability levels (e.g., resident cost burdens, costs relative to market average)
* Economic impact
* Quality-of-life (e.g., access to jobs, transportation)
* Sustainability (HTF performance and ROI)
* Partner satisfaction (surveys and feedback from stakeholders)

## IMPORTANT CONSIDERATIONS

* Staff should conduct an assessment of new legal and financial liabilities that accrue from  administering funds from new sources—including local governments, banks, corporations, and charitable institutions. When funds are provided to the HTF from any of these sources in the form of grants, the HTF should have a standard set of requirements outlined in the grant agreement, including clarity around procedures and reporting for liability, lending, and grant making.
* Staff should evaluate the capacity to undertake traditional bank style “underwriting” if HTF awards are structured as loans. Additional training may be needed, as well as potential upgrades to accounting programs and other software.
* If some tasks are too burdensome for staff, a qualified third party could be hired to conduct underwriting, service loans, process payments, and other related duties. It is possible to outsource these functions to a community lending institution or to Virginia Community Capital, Virginia’s statewide community development financial institution (CDFI).

## EXAMPLES

**[New River Valley Housing Trust Fund](https://nrvrc.org/nrv-housing-trust-fund)**

* Brand-new and seeded with a Virginia Housing PDC grant
* Regional oversight board (appointed by New River Valley Regional Commission) will help staff evaluate proposals; final approval by NRVRC Board

**[Arlington Affordable Housing Investment Fund](https://www.arlingtonva.us/Government/Programs/Housing/Development/Affordable-Housing-Investment-Fund)**

* Mix of dedicated county revenue sources (e.g. recordation tax) and traditional federal funds
* Led by staff; awards are officially approved through advisory committee and board of supervisors

**[Alexandria Housing Opportunities Fund](https://media.alexandriava.gov/docs-archives/housing/info/2020=hofapplicationprocessrequirements.pdf)**

* Funded by developer payments (in lieu of providing affordable units), 1 cent real estate tax, and 1% increment of meals tax
* Led by staff; awards are officially approved through advisory committee and board of supervisors
